### ISSUE TITLE
OpenRL

### ISSUE THREAD

**Issue by KorolevSoftware** [KickRooster/Radiosity#1]
Hi, I am looking for documentation about OpenL. But I can’t find anywhere. You can give me a link to the documentation and examples OpenL ? I'll be very grateful. And the question is whether it makes sense to use OpenRL in 2019 ?

**Comment by KickRooster** [comment]
Hi, I have searched for a while for finding the SDK of OpenRL, but I got no result, I don't know why.... https://github.com/galdar496/heatray, this repository is a ecelcent example for learning OpenRL.
And as I know, for the kernel conpect e.g. different kinds of shaders for hardware ray tracing, both OpenRL and DX12 or Vulkan are all same, so you can go to learn the newer ones. : ) 
For hardware acceleration rendering when using OpenRL, you must buy a hardware, otherwise the calculation of ray cast will be running on CPU.

**Comment by KickRooster** [comment]
http://imgtec.eetrend.com/sites/imgtec.eetrend.com/files/article/201402/1495-2162-1.pdf a simpler pdf.

**Comment by KorolevSoftware** [comment]
I am sorry. I saw your answer only today. Thanks your for the detailed answer.
